CREATE TABLE `zerocup`.`note` (
  `id` INT NOT NULL,
  `TITLE` TEXT NULL,
  `USER` VARCHAR(45) NULL,
  `LONGITUDE` DOUBLE NULL,
  `LATITUDE` DOUBLE NULL,
  `POI` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `USER_idx` (`USER` ASC),
  INDEX `POI_idx` (`POI` ASC),
  CONSTRAINT `USER`
    FOREIGN KEY (`USER`)
    REFERENCES `zerocup`.`user` (`USERNAME`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `POI`
    FOREIGN KEY (`POI`)
    REFERENCES `zerocup`.`poi` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);
